spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    host: ${DATABASE_HOST}
    port: ${DATABASE_PORT}
    database: ${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 20
      validation-query: SELECT 1
      max-idle-time: 30m

  flyway:
    baseline-on-migrate: false

strategy:
  bollinger-bands-trend:
    entry-amount: 100
    leverage: 5
    time-period: 15m
    universe:
      - XRPUSDT
      - DOGEUSDT
      - ETHUSDT
      - SOLUSDT

logging:
  level:
    org.springframework.r2dbc.core: debug