spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    host: ${DATABASE_HOST}
    port: ${DATABASE_PORT}
    database: ${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  flyway:
    baseline-on-migrate: false

logging:
  level:
    org.springframework.r2dbc.core: debug